package ircd

const (
	ERR_NOSUCHNICK       string = ":%s 401 %s %s :No such nick/channel"
	ERR_NOSUCHSERVER            = ":%s 402 %s :No such server"
	ERR_NOSUCHCHANNEL           = ":%s 403 %s %s :No such channel"
	ERR_CANNOTSENDTOCHAN        = ":%s 404 %s %s :Cannot send to channel"
	ERR_TOOMANYCHANNELS         = ":%s 405 %s :You have joined too many channels"
	ERR_WASNOSUCHNICK           = ":%s 406 %s :There was no such nickname"
	ERR_TOOMANYTARGETS          = ":%s 407 %s :Duplicate recipients. No message delivered"
	ERR_NOORIGIN                = ":%s 409 :No origin specified"
	ERR_NORECIPIENT             = ":%s 411 %s :No recipient given (%s)"
	ERR_NOTEXTTOSEND            = ":%s 412 %s :No text to send"
	ERR_NOTOPLEVEL              = ":%s 413 %s :No toplevel domain specified"
	ERR_WILDTOPLEVEL            = ":%s 414 %s :Wildcard in toplevel domain"
	ERR_UNKNOWNCOMMAND          = ":%s 421 %s %s :Unknown command"
	ERR_NOMOTD                  = ":%s 422 :MOTD File is missing"
	ERR_NOADMININFO             = ":%s 423 %s :No administrative info available"
	ERR_NONICKNAMEGIVEN         = ":%s 431 :No nickname given"
	ERR_ERRONEUSNICKNAME        = ":%s 432 %s :Erroneus nickname"
	ERR_NICKNAMEINUSE           = ":%s 433 %s :Nickname is already in use"
	ERR_NICKCOLLISION           = ":%s 436 %s :Nickname collision KILL"
	ERR_USERNOTINCHANNEL        = ":%s 441 %s %s :They aren't on that channel"
	ERR_NOTONCHANNEL            = ":%s 442 %s %s :You're not on that channel"
	ERR_USERONCHANNEL           = ":%s 443 %s %s :is already on channel"
	ERR_NOLOGIN                 = ":%s 444 %s :User not logged in"
	ERR_SUMMONDISABLED          = ":%s 445 :SUMMON has been disabled"
	ERR_USERSDISABLED           = ":%s 446 :USERS has been disabled"
	ERR_NOTREGISTERED           = ":%s 451 :You have not registered"
	ERR_NEEDMOREPARAMS          = ":%s 461 %s %s :Not enough parameters"
	ERR_ALREADYREGISTRED        = ":%s 462 %s :You may not reregister"
	ERR_NOPERMFORHOST           = ":%s 463 :Your host isn't among the privileged"
	ERR_PASSWDMISMATCH          = ":%s 464 :Password incorrect"
	ERR_YOUREBANNEDCREEP        = ":%s 465 :You are banned from this server"
	ERR_KEYSET                  = ":%s 467 %s :Channel key already set"
	ERR_CHANNELISFULL           = ":%s 471 %s :Cannot join channel (+l)"
	ERR_UNKNOWNMODE             = ":%s 472 %s :is unknown mode char to me"
	ERR_INVITEONLYCHAN          = ":%s 473 %s %s :Cannot join channel (+i)"
	ERR_BANNEDFROMCHAN          = ":%s 474 %s :Cannot join channel (+b)"
	ERR_BADCHANNELKEY           = ":%s 475 %s :Cannot join channel (+k)"
	ERR_NOPRIVILEGES            = ":%s 481 :Permission Denied- You're not an IRC operator"
	ERR_CHANOPRIVSNEEDED        = ":%s 482 %s :You're not channel operator"
	ERR_CANTKILLSERVER          = ":%s 483 :You cant kill a server!"
	ERR_NOOPERHOST              = ":%s 491 :No O-lines for your host"
	ERR_UMODEUNKNOWNFLAG        = ":%s 501 :Unknown MODE flag"
	ERR_USERSDONTMATCH          = ":%s 502 :Cant change mode for other users"

	RPL_NOTOPIC   = ":%s 331 %s %s :No topic is set"
	RPL_TOPIC     = ":%s 332 %s %s :%s"
	RPL_YOUREOPER = ":%s 381 You are now an IRC operator"
)
